services:
  - type: web
    name: hairstory-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ASSISTANT_ID
        sync: false 